-- Revoke and drop the least-privilege app role.
REVOKE ALL ON ALL TABLES IN SCHEMA kerp FROM kerp_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA kerp FROM kerp_app;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA kerp, public FROM kerp_app;
REVOKE USAGE ON SCHEMA kerp, public FROM kerp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA kerp REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM kerp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA kerp REVOKE USAGE, SELECT ON SEQUENCES FROM kerp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA kerp REVOKE EXECUTE ON FUNCTIONS FROM kerp_app;
DROP ROLE IF EXISTS kerp_app;
