// Tax Invoice Service Protocol Buffer Definition
// K-ERP SaaS - Phase 5: Tax/Hometax Integration

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: tax/v1/tax.proto

package taxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TaxInvoiceService_Login_FullMethodName                      = "/kerp.tax.v1.TaxInvoiceService/Login"
	TaxInvoiceService_Logout_FullMethodName                     = "/kerp.tax.v1.TaxInvoiceService/Logout"
	TaxInvoiceService_GetTaxInvoices_FullMethodName             = "/kerp.tax.v1.TaxInvoiceService/GetTaxInvoices"
	TaxInvoiceService_IssueTaxInvoice_FullMethodName            = "/kerp.tax.v1.TaxInvoiceService/IssueTaxInvoice"
	TaxInvoiceService_CancelTaxInvoice_FullMethodName           = "/kerp.tax.v1.TaxInvoiceService/CancelTaxInvoice"
	TaxInvoiceService_GetTaxInvoiceStatus_FullMethodName        = "/kerp.tax.v1.TaxInvoiceService/GetTaxInvoiceStatus"
	TaxInvoiceService_SyncFromHometax_FullMethodName            = "/kerp.tax.v1.TaxInvoiceService/SyncFromHometax"
	TaxInvoiceService_StreamInvoiceNotifications_FullMethodName = "/kerp.tax.v1.TaxInvoiceService/StreamInvoiceNotifications"
	TaxInvoiceService_HealthCheck_FullMethodName                = "/kerp.tax.v1.TaxInvoiceService/HealthCheck"
)

// TaxInvoiceServiceClient is the client API for TaxInvoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaxInvoiceServiceClient interface {
	// Login to Hometax with certificate or credentials
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Logout and invalidate session
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// Retrieve tax invoices from Hometax
	GetTaxInvoices(ctx context.Context, in *GetTaxInvoicesRequest, opts ...grpc.CallOption) (*GetTaxInvoicesResponse, error)
	// Issue a new tax invoice via Hometax
	IssueTaxInvoice(ctx context.Context, in *IssueTaxInvoiceRequest, opts ...grpc.CallOption) (*IssueTaxInvoiceResponse, error)
	// Cancel an issued tax invoice
	CancelTaxInvoice(ctx context.Context, in *CancelTaxInvoiceRequest, opts ...grpc.CallOption) (*CancelTaxInvoiceResponse, error)
	// Get status of a specific tax invoice
	GetTaxInvoiceStatus(ctx context.Context, in *GetTaxInvoiceStatusRequest, opts ...grpc.CallOption) (*GetTaxInvoiceStatusResponse, error)
	// Sync tax invoices from Hometax into the caller's own store.
	SyncFromHometax(ctx context.Context, in *SyncFromHometaxRequest, opts ...grpc.CallOption) (*SyncFromHometaxResponse, error)
	// Stream real-time invoice notifications.
	//
	// The Python servicer aborts this with UNIMPLEMENTED - it is declared here so
	// the two service definitions stay method-for-method identical, not because a
	// caller can use it.
	StreamInvoiceNotifications(ctx context.Context, in *StreamNotificationsRequest, opts ...grpc.CallOption) (TaxInvoiceService_StreamInvoiceNotificationsClient, error)
	// Service-specific health check, reporting each dependency separately.
	// The standard grpc.health.v1.Health service is also served and is the one
	// exempt from the token interceptor; prefer it for liveness probes.
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type taxInvoiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaxInvoiceServiceClient(cc grpc.ClientConnInterface) TaxInvoiceServiceClient {
	return &taxInvoiceServiceClient{cc}
}

func (c *taxInvoiceServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_Logout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) GetTaxInvoices(ctx context.Context, in *GetTaxInvoicesRequest, opts ...grpc.CallOption) (*GetTaxInvoicesResponse, error) {
	out := new(GetTaxInvoicesResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_GetTaxInvoices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) IssueTaxInvoice(ctx context.Context, in *IssueTaxInvoiceRequest, opts ...grpc.CallOption) (*IssueTaxInvoiceResponse, error) {
	out := new(IssueTaxInvoiceResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_IssueTaxInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) CancelTaxInvoice(ctx context.Context, in *CancelTaxInvoiceRequest, opts ...grpc.CallOption) (*CancelTaxInvoiceResponse, error) {
	out := new(CancelTaxInvoiceResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_CancelTaxInvoice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) GetTaxInvoiceStatus(ctx context.Context, in *GetTaxInvoiceStatusRequest, opts ...grpc.CallOption) (*GetTaxInvoiceStatusResponse, error) {
	out := new(GetTaxInvoiceStatusResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_GetTaxInvoiceStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) SyncFromHometax(ctx context.Context, in *SyncFromHometaxRequest, opts ...grpc.CallOption) (*SyncFromHometaxResponse, error) {
	out := new(SyncFromHometaxResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_SyncFromHometax_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taxInvoiceServiceClient) StreamInvoiceNotifications(ctx context.Context, in *StreamNotificationsRequest, opts ...grpc.CallOption) (TaxInvoiceService_StreamInvoiceNotificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TaxInvoiceService_ServiceDesc.Streams[0], TaxInvoiceService_StreamInvoiceNotifications_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &taxInvoiceServiceStreamInvoiceNotificationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaxInvoiceService_StreamInvoiceNotificationsClient interface {
	Recv() (*InvoiceNotification, error)
	grpc.ClientStream
}

type taxInvoiceServiceStreamInvoiceNotificationsClient struct {
	grpc.ClientStream
}

func (x *taxInvoiceServiceStreamInvoiceNotificationsClient) Recv() (*InvoiceNotification, error) {
	m := new(InvoiceNotification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taxInvoiceServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, TaxInvoiceService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaxInvoiceServiceServer is the server API for TaxInvoiceService service.
// All implementations should embed UnimplementedTaxInvoiceServiceServer
// for forward compatibility
type TaxInvoiceServiceServer interface {
	// Login to Hometax with certificate or credentials
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Logout and invalidate session
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// Retrieve tax invoices from Hometax
	GetTaxInvoices(context.Context, *GetTaxInvoicesRequest) (*GetTaxInvoicesResponse, error)
	// Issue a new tax invoice via Hometax
	IssueTaxInvoice(context.Context, *IssueTaxInvoiceRequest) (*IssueTaxInvoiceResponse, error)
	// Cancel an issued tax invoice
	CancelTaxInvoice(context.Context, *CancelTaxInvoiceRequest) (*CancelTaxInvoiceResponse, error)
	// Get status of a specific tax invoice
	GetTaxInvoiceStatus(context.Context, *GetTaxInvoiceStatusRequest) (*GetTaxInvoiceStatusResponse, error)
	// Sync tax invoices from Hometax into the caller's own store.
	SyncFromHometax(context.Context, *SyncFromHometaxRequest) (*SyncFromHometaxResponse, error)
	// Stream real-time invoice notifications.
	//
	// The Python servicer aborts this with UNIMPLEMENTED - it is declared here so
	// the two service definitions stay method-for-method identical, not because a
	// caller can use it.
	StreamInvoiceNotifications(*StreamNotificationsRequest, TaxInvoiceService_StreamInvoiceNotificationsServer) error
	// Service-specific health check, reporting each dependency separately.
	// The standard grpc.health.v1.Health service is also served and is the one
	// exempt from the token interceptor; prefer it for liveness probes.
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
}

// UnimplementedTaxInvoiceServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTaxInvoiceServiceServer struct {
}

func (UnimplementedTaxInvoiceServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) GetTaxInvoices(context.Context, *GetTaxInvoicesRequest) (*GetTaxInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaxInvoices not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) IssueTaxInvoice(context.Context, *IssueTaxInvoiceRequest) (*IssueTaxInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueTaxInvoice not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) CancelTaxInvoice(context.Context, *CancelTaxInvoiceRequest) (*CancelTaxInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTaxInvoice not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) GetTaxInvoiceStatus(context.Context, *GetTaxInvoiceStatusRequest) (*GetTaxInvoiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaxInvoiceStatus not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) SyncFromHometax(context.Context, *SyncFromHometaxRequest) (*SyncFromHometaxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncFromHometax not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) StreamInvoiceNotifications(*StreamNotificationsRequest, TaxInvoiceService_StreamInvoiceNotificationsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamInvoiceNotifications not implemented")
}
func (UnimplementedTaxInvoiceServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}

// UnsafeTaxInvoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaxInvoiceServiceServer will
// result in compilation errors.
type UnsafeTaxInvoiceServiceServer interface {
	mustEmbedUnimplementedTaxInvoiceServiceServer()
}

func RegisterTaxInvoiceServiceServer(s grpc.ServiceRegistrar, srv TaxInvoiceServiceServer) {
	s.RegisterService(&TaxInvoiceService_ServiceDesc, srv)
}

func _TaxInvoiceService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_GetTaxInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).GetTaxInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_GetTaxInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).GetTaxInvoices(ctx, req.(*GetTaxInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_IssueTaxInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTaxInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).IssueTaxInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_IssueTaxInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).IssueTaxInvoice(ctx, req.(*IssueTaxInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_CancelTaxInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaxInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).CancelTaxInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_CancelTaxInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).CancelTaxInvoice(ctx, req.(*CancelTaxInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_GetTaxInvoiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxInvoiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).GetTaxInvoiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_GetTaxInvoiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).GetTaxInvoiceStatus(ctx, req.(*GetTaxInvoiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_SyncFromHometax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFromHometaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).SyncFromHometax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_SyncFromHometax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).SyncFromHometax(ctx, req.(*SyncFromHometaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaxInvoiceService_StreamInvoiceNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNotificationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaxInvoiceServiceServer).StreamInvoiceNotifications(m, &taxInvoiceServiceStreamInvoiceNotificationsServer{stream})
}

type TaxInvoiceService_StreamInvoiceNotificationsServer interface {
	Send(*InvoiceNotification) error
	grpc.ServerStream
}

type taxInvoiceServiceStreamInvoiceNotificationsServer struct {
	grpc.ServerStream
}

func (x *taxInvoiceServiceStreamInvoiceNotificationsServer) Send(m *InvoiceNotification) error {
	return x.ServerStream.SendMsg(m)
}

func _TaxInvoiceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaxInvoiceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaxInvoiceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaxInvoiceServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TaxInvoiceService_ServiceDesc is the grpc.ServiceDesc for TaxInvoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaxInvoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kerp.tax.v1.TaxInvoiceService",
	HandlerType: (*TaxInvoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _TaxInvoiceService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _TaxInvoiceService_Logout_Handler,
		},
		{
			MethodName: "GetTaxInvoices",
			Handler:    _TaxInvoiceService_GetTaxInvoices_Handler,
		},
		{
			MethodName: "IssueTaxInvoice",
			Handler:    _TaxInvoiceService_IssueTaxInvoice_Handler,
		},
		{
			MethodName: "CancelTaxInvoice",
			Handler:    _TaxInvoiceService_CancelTaxInvoice_Handler,
		},
		{
			MethodName: "GetTaxInvoiceStatus",
			Handler:    _TaxInvoiceService_GetTaxInvoiceStatus_Handler,
		},
		{
			MethodName: "SyncFromHometax",
			Handler:    _TaxInvoiceService_SyncFromHometax_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _TaxInvoiceService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInvoiceNotifications",
			Handler:       _TaxInvoiceService_StreamInvoiceNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tax/v1/tax.proto",
}
